
before_install:
    - echo "Before Install"

ros_install:
    - robot-localization
    - mavros
    - mavros-extras
    - mavlink

install:
    - sudo apt-get install ipython

before_script:
    - echo "Before Script"

script:
    - catkin_make

after_script:
    - echo "After Script"

before_deploy:
    - echo "Before Deploy"

deploy:
    - roslaunch foresight bench_test.launch

after_deploy:
    - echo "After Deploy"
